matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      env: "iOS 10 - Swift 3.1"
      install:
        - carthage update --platform ios --no-use-binaries
      script:
        - set -o pipefail && xcodebuild -scheme DBEmptyState -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      osx_image: xcode9
      language: objective-c
      env: "iOS 11 - Swift 3.2/4.0"
      install:
        - carthage update --platform ios --no-use-binaries
      script:
        - set -o pipefail && xcodebuild -scheme DBEmptyState -destination 'platform=iOS Simulator,name=iPhone SE,OS=latest' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)